export default {
    en: {
        main_title: 'Don\'t get lost!',
        main_text: 'Documents attached to your ID in WANTED.Im, <br>They will find you in case of their loss.',
        what_doc: 'Document type',
        what_number: 'Document number',
        what_date: 'Date of issue',
        what_validity: 'Validity',
        owner: 'Owner',
        issued: 'Issued by',
        btn_lost_found: 'My logbook',
        tie: 'Attach to ID',
        title: 'Document title',
        found: 'Find owner',
        find_owner: 'Find owner',
        policy_link: 'Private policy',
        form_ready: 'Almost ready',
        form_ready_attach: 'Everything will be OK!',
        form_ready_text: 'It remains to add only the phone. By this phone number, you can quickly contact you if someone finds your documents.',
        form_ready_text_attach: 'Insert your mobile number to be available.',
        phone_number: 'Phone number',
        send_sms: 'Send SMS',
        back: 'back',
        sms_sended: 'SMS sent',
        on_phone: 'An SMS was sent to',
        sms_with_code: 'with the code necessary to activate your personal account.',
        not_received: 'Have not received?',
        resend: 'Send SMS again',
        code_from: 'SMS code',
        edit_phone: 'Edit phone',
        enter_acc: 'Log in',
        doc_photo: 'Personal ID<br>(with photo)',
        doc_no_photo: 'Certificate<br>(without photo)',
        plastic: 'Plastic card',
        1: 'Personal ID',
        2: 'Certificate',
        3: 'Plastic card',
        logout: 'Log out',
        page_found: 'Found',
        page_lost: 'Items',
        action: 'Action',
        select: 'Select',
        doc: 'Document',
        will_remove: 'will remove after',
        second: 'second',
        cancel: 'Cancel',
        remove_limit: 'You can remove only 3 document in same time',
        again_enter_acc: 'Again send cmc',
        no_docs: 'No any document',
        no_founds: 'Documents not found',
        remove: 'Remove',
        edit: 'Edit',
        valid: 'Looks good',
        invalid: 'Invalid',
        invalidNumber: 'Only characters, numbers and latin',
        invalidOwner: 'Only character',
        validIssue: 'Only character and numbers',
        invalidCode: 'Invalid code format',
        code_timer: ' Resend link appear after ',
        edit_doc: 'Edit document',
        save: 'Save',
        attach: 'Attach to your account',
        found_doc: 'Found document',
        doc_phone_owner: 'Owner phone',
        empty: 'Field is required',
        emptyNumber: 'Please select a type and specify a document number',
        wrongCode: 'Wrong confirmation code',
        want_back: 'Want to return a found document?',
        contact_owner: 'Contact with owner',
        find: 'Find',
        will_restore: 'Can restore until',
        restore: 'restore',
        inner_phone_text: 'Enter your phone number to receive a verification code. Then you can find out the phone number of the owner of the document.',
    },
    ru: {
        main_title: 'Не теряйся!',
        main_text: 'Документы, привязанные к Вашему ID в WANTED.Im, <br>сами найдут Вас в случае их пропажи.',
        what_doc: 'Тип документа',
        what_number: 'Номер документа',
        what_date: 'Дата выдачи',
        what_validity: 'Срок действия',
        owner: ' Владелец',
        issued: 'Кем выдан',
        btn_lost_found: 'Мой журнал',
        tie: 'Привязать к ID',
        title: 'Название документа',
        found: 'Найти владельца',
        find_owner: 'Найти владельца',
        policy_link: 'Пользовательское соглашение',
        form_ready: 'Вход в аккаунт',
        form_ready_attach: 'Всё будет хорошо!',
        form_ready_text: 'Введите номер телефона для получения кода подтверждения. По указанному номеру с вами свяжется  нашедший ваши документы.',
        form_ready_text_attach: 'Оставьте свой мобильный номер и оставайтесь в доступе.',
        phone_number: 'Номер телефона',
        send_sms: 'Отправить СМС',
        back: 'Назад',
        sms_sended: 'Отправили SMS',
        on_phone: 'На телефон',
        sms_with_code: 'отправлено SMS с кодом подтверждения.',
        not_received: 'Получили СМС?',
        resend: 'Отправить SMS повоторно',
        code_from: 'Код из SMS',
        edit_phone: 'Изменить телефон',
        enter_acc: 'Войти в аккаунт',
        doc_photo: 'Удостоверение<br>(с фото)',
        doc_no_photo: 'Свидетельство<br>(без фото)',
        plastic: 'Пластиковая карта',
        1: 'Удостоверение',
        2: 'Свидетельство',
        3: 'Пластиковая карта',
        logout: 'Выход',
        page_found: 'Находки',
        page_lost: 'Объекты',
        action: 'Действие',
        select: 'Выбор',
        doc: 'Документ',
        will_remove: 'будет удален через',
        second: 'секунд',
        cancel: 'Отменить',
        remove_limit: 'Вы можете удалять только 3 документа в одно время',
        again_enter_acc: 'Отправить снова',
        no_docs: 'Нет подходящих документов',
        no_founds: 'Документы не найдены',
        remove: 'Удалить',
        edit: 'Редактировать',
        valid: 'Верно',
        invalid: 'Ошибка',
        invalidNumber: 'Только символы, цифры и латинские буквы',
        emptyNumber: 'Пожалуйста, выберите тип и укажите номер документа',
        invalidOwner: 'Только буквы',
        validIssue: 'Только буквы и цифры',
        invalidCode: 'Неверный формат кода',
        code_timer: ' Ссылка для повторной отправки кода появится через ',
        edit_doc: 'Редактировать документ',
        save: 'Сохранить',
        attach: 'Добавить документ к себе',
        found_doc: 'Нашли документ',
        doc_phone_owner: 'Телефон владельца',
        empty: 'Поле обязательно для заполненния',
        wrongCode: 'Вы ввели неверный код',
        want_back: 'Хотите вернуть найденный документ?',
        contact_owner: 'Контакт с владельцем',
        find: 'Найти',
        will_restore: 'можно восстановить в течение',
        restore: 'восстановить',
        inner_phone_text: 'Введите номер телефона для получения кода подтверждения. После вы сможете узнать номер телефона владельца документа.',
    },
};
